import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import { M_PLUS_Rounded_1c, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";

const MPlusRounded1c = M_PLUS_Rounded_1c({
  variable: "--font-m-plus-rounded-1c",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="pastel" className="scroll-pt-16 scroll-smooth">
      <body className={`${MPlusRounded1c.variable} ${geistSans.variable} ${geistMono.variable}`}>
        {/* Header */}
        <Navbar />
        {/* Main content */}
        <div className="shadow-xs bg-base-200">{children}</div>
        {/* Footer */}
        <footer className="p-4 container mx-auto">
          <aside>
            <Link href="/">
              <Image
                src="/logo-vertical-transparent.svg"
                className="mb-4"
                width={150}
                height={31.5}
                alt=""
              />
            </Link>
            <p className="font-bold">AI Media powered by AI</p>
            <p>Copyright © {new Date().getFullYear()} - All right reserved</p>
          </aside>
        </footer>
      </body>
    </html>
  );
}
