import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import { M_PLUS_Rounded_1c, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";

const MPlusRounded1c = M_PLUS_Rounded_1c({
  variable: "--font-m-plus-rounded-1c",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="pastel" className="scroll-pt-16 scroll-smooth">
      <body className={`${MPlusRounded1c.variable} ${geistSans.variable} ${geistMono.variable}`}>
        {/* Header */}
        <Navbar />
        {/* Main content */}
        <div className="shadow-xs bg-base-200">{children}</div>
        {/* Footer */}
        <footer className="items-center p-6 text-base-content border-t border-base-300">
          <div className="container mx-auto px-4">
            <div className="flex flex-col md:flex-row items-center justify-between w-full gap-4">
              <div className="flex items-center gap-3">
                <Link href="/">
                  <Image
                    src="/logo-vertical-transparent.svg"
                    className="mb-4"
                    width={150}
                    height={31.5}
                    alt=""
                  />
                </Link>
              </div>

              <div className="text-center text-sm md:text-base font-medium">
                AI Media powered by AI
              </div>

              <div className="text-sm text-gray-500 text-center md:text-right">
                © 2025 All rights reserved
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
